/**
 * Site Routes Configuration
 * Central configuration data for all routes, page classes, and transition data
 * Separated from SiteConfig class logic for better maintainability
 */

export const siteRoutes = {
  'home': {
    template: "home",
    class: "Home",
    link: "/",
    url: "/pages/index.html",
    title: "The Shea Memorandum",
    metaDescription: "The Shea Memorandum examines Israeli surveillance of 9/11 hijackers and FBI suspects, revealing critical intelligence failures before September 11, 2001.",
    transition: {
      image: "https://shea-memorandum-site.b-cdn.net/images/home-section-desktop.webp",
      copy: "The Shea Memorandum",
      alt: "The Shea Memorandum",
    },
  },
  'introduction': {
    template: "introduction",
    class: "Introduction",
    link: "/introduction",
    url: "/pages/introduction.html",
    title: "Introduction",
    metaDescription: "Introduction to The Shea Memorandum: A comprehensive investigation into Israeli surveillance of future 9/11 hijackers and the failure to provide adequate warning.",
    transition: {
      image: "https://shea-memorandum-site.b-cdn.net/images/home-theme-desktop.webp",
      copy: "Introduction",
      alt: "Introduction",
    },
  },
  "section-1": {
    template: "section-1",
    class: "View",
    link: "/section-1",
    url: "/pages/section-1.html",
    title: "General Preliminary Conclusions",
    metaDescription: "General preliminary conclusions from The Shea Memorandum regarding Israeli DEA groups' surveillance of 9/11 hijackers before the attacks.",
    transition: {
      image: "https://shea-memorandum-site.b-cdn.net/images/section-1-desktop.webp",
      copy: "General Preliminary Conclusions",
      alt: "General Preliminary Conclusions",
    },
  },
  "section-2": {
    template: "section-2",
    class: "View",
    link: "/section-2",
    url: "/pages/section-2.html",
    title: "Imperatives and Priorities",
    metaDescription: "Examining the imperatives and priorities in investigating 9/11 attacks, focusing on justice, national security, and preventing future attacks.",
    transition: {
      image: "https://shea-memorandum-site.b-cdn.net/images/section-2-desktop.webp",
      copy: "Imperatives and Priorities",
      alt: "Imperatives and Priorities",
    },
  },
  "section-3": {
    template: "section-3",
    class: "View",
    link: "/section-3",
    url: "/pages/section-3.html",
    title: "The DEA Report",
    metaDescription: "Analysis of the DEA report documenting Israeli surveillance groups and their activities related to 9/11 hijackers and FBI suspects.",
    transition: {
      image: "https://shea-memorandum-site.b-cdn.net/images/section-3-desktop.webp",
      copy: "The DEA Report",
      alt: "The DEA Report",
    },
  },
  "section-4": {
    template: "section-4",
    class: "View",
    link: "/section-4",
    url: "/pages/section-4.html",
    title: "The Israeli DEA Groups",
    metaDescription: "Detailed examination of Israeli DEA groups involved in surveillance operations targeting 9/11 hijackers before September 11, 2001.",
    transition: {
      image: "https://shea-memorandum-site.b-cdn.net/images/section-4-desktop.webp",
      copy: "The Israeli DEA Groups",
      alt: "The Israeli DEA Groups",
    },
  },
  "section-5": {
    template: "section-5",
    class: "View",
    link: "/section-5",
    url: "/pages/section-5.html",
    title: "The Future Hijackers and FBI Suspects",
    metaDescription: "Investigation into the future 9/11 hijackers and FBI suspects, their locations, activities, and connections to Israeli surveillance operations.",
    transition: {
      image: "https://shea-memorandum-site.b-cdn.net/images/section-5-desktop.webp",
      copy: "The Future Hijackers and FBI Suspects",
      alt: "The Future Hijackers and FBI Suspects",
    },
  },
  "section-6": {
    template: "section-6",
    class: "View",
    link: "/section-6",
    url: "/pages/section-6.html",
    title: "Reports Concerning the Surveillance Activities of the Israeli DEA Groups",
    metaDescription: "Reports and evidence documenting surveillance activities conducted by Israeli DEA groups on 9/11 hijackers before the September 11 attacks.",
    transition: {
      image: "https://shea-memorandum-site.b-cdn.net/images/section-6-desktop.webp",
      copy: "Reports Concerning the Surveillance Activities of the Israeli DEA Groups",
      alt: "Reports Concerning the Surveillance Activities of the Israeli DEA Groups",
    },
  },
  "section-7": {
    template: "section-7",
    class: "View",
    link: "/section-7",
    url: "/pages/section-7.html",
    title: "Northeastern New Jersey—Another Vital Center of Operations for Both Sides",
    metaDescription: "Northeastern New Jersey as a critical operations center for both 9/11 hijackers and Israeli DEA surveillance groups before the attacks.",
    transition: {
      image: "https://shea-memorandum-site.b-cdn.net/images/section-7-desktop.webp",
      copy: "Northeastern New Jersey—Another Vital Center of Operations for Both Sides",
      alt: "Northeastern New Jersey—Another Vital Center of Operations for Both Sides",
    },
  },
  "section-8": {
    template: "section-8",
    class: "View",
    link: "/section-8",
    url: "/pages/section-8.html",
    title: "Inadequate Israeli Warnings in August 2001",
    metaDescription: "Analysis of inadequate warnings provided by Israeli intelligence in August 2001 regarding the impending 9/11 terrorist attacks.",
    transition: {
      image: "https://shea-memorandum-site.b-cdn.net/images/section-8-desktop.webp",
      copy: "Inadequate Israeli Warnings in August 2001",
      alt: "Inadequate Israeli Warnings in August 2001",
    },
  },
  "section-9": {
    template: "section-9",
    class: "View",
    link: "/section-9",
    url: "/pages/section-9.html",
    title: "The Watchlisting of Khaled al Mihdhar and Nawaf al Hazmi in August 2001",
    metaDescription: "Critical examination of the watchlisting process for 9/11 hijackers Khaled al Mihdhar and Nawaf al Hazmi in August 2001.",
    transition: {
      image: "https://shea-memorandum-site.b-cdn.net/images/section-9-desktop.webp",
      copy: "The Watchlisting of Khaled al Mihdhar and Nawaf al Hazmi in August 2001",
      alt: "The Watchlisting of Khaled al Mihdhar and Nawaf al Hazmi in August 2001",
    },
  },
  "section-10": {
    template: "section-10",
    class: "View",
    link: "/section-10",
    url: "/pages/section-10.html",
    title: "Why the Israeli Groups?",
    metaDescription: "Investigating why Israeli DEA groups were surveilling 9/11 hijackers and the implications of their surveillance activities.",
    transition: {
      image: "https://shea-memorandum-site.b-cdn.net/images/section-10-desktop.webp",
      copy: "Why the Israeli Groups?",
      alt: "Why the Israeli Groups?",
    },
  },
  "section-11": {
    template: "section-11",
    class: "View",
    link: "/section-11",
    url: "/pages/section-11.html",
    title: "The CIA's Role and Responsibilities",
    metaDescription: "The CIA's role and responsibilities in investigating Israeli surveillance of 9/11 hijackers and the failure to provide adequate warning.",
    transition: {
      image: "https://shea-memorandum-site.b-cdn.net/images/section-11-desktop.webp",
      copy: "The CIA's Role and Responsibilities",
      alt: "The CIA's Role and Responsibilities",
    },
  },
  "section-12": {
    template: "section-12",
    class: "View",
    link: "/section-12",
    url: "/pages/section-12.html",
    title: "Detailed Summary",
    metaDescription: "Comprehensive detailed summary of The Shea Memorandum findings on Israeli surveillance of 9/11 hijackers and intelligence failures.",
    transition: {
      image: "https://shea-memorandum-site.b-cdn.net/images/section-12-desktop.webp",
      copy: "Detailed Summary",
      alt: "Detailed Summary",
    },
  },
  'media': {
    template: "section-media",
    class: "View",
    link: "/media",
    url: "/pages/media.html",
    title: "Media Stories & Reports",
    metaDescription: "Media stories and reports covering The Shea Memorandum, Israeli surveillance of 9/11 hijackers, and related intelligence investigations.",
    transition: {
      image: "https://shea-memorandum-site.b-cdn.net/images/section-media-desktop.webp",
      copy: "The Shea Memorandum",
      alt: "The Shea Memorandum",
    },
  },
  'manifest': {
    template: "manifest",
    class: "View",
    link: "/manifest",
    url: "/pages/manifest.html",
    title: "Art Students & Intelligence Backgrounds Manifest",
    metaDescription: "The Art Students and Intelligence Backgrounds Manifest documenting Israeli individuals with intelligence connections before 9/11.",
    transition: {
      image: "https://shea-memorandum-site.b-cdn.net/images/section-manifest-desktop.webp",
      copy: "Manifest",
      alt: "Manifest",
    },
  },
  'references': {
    template: "references",
    class: "View",
    link: "/references",
    url: "/pages/references.html",
    title: "References",
    metaDescription: "Complete references and citations for The Shea Memorandum on Israeli surveillance of 9/11 hijackers and intelligence failures.",
    transition: {
      image: "https://shea-memorandum-site.b-cdn.net/images/home-theme-desktop.webp",
      copy: "References",
      alt: "References",
    },
  },
};
